project_name: natscli

release:
  github:
    owner: nats-io
    name: natscli
  name_template: "Release {{.Tag}}"
  draft: true

changelog:
  skip: true

builds:
  - main: ./nats
    id: nats
    binary: nats
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: 386

archives:
  - name_template: "nats-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

brews:
  - name: nats
    folder: Formula
    tap:
      owner: nats-io
      name: homebrew-nats-tools
    url_template: "https://github.com/nats-io/natscli/releases/download/{{ .Tag }}/nats-{{.Version}}-{{ .Os }}-{{ .Arch }}{{if .Arm}}{{.Arm}}{{end}}.zip"
    homepage: "https://github.com/nats-io/nats"
    description: "NATS utility"
    skip_upload: false
    test: |
      system "#{bin}/nats --version"
    install: |
      bin.install "nats"

nfpms:
  - file_name_template: 'nats-{{.Tag}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    homepage:  https://nats.io
    description: NATS Utility
    maintainer: R.I. Pienaar <rip@devco.net>
    license: Apache 2.0
    vendor: Synadia Inc.
    formats:
      - deb
      - rpm
